import Head from "next/head";
import Hero from "./componants/Hero";
import Instagram from "./componants/instagram";
import Slider from "./componants/Slider";
import { SliderData } from "./componants/sliderData";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero
        heading="chik Photography"
        message="i capture moments in nature and keep them alive"
      />
      <Slider slides={SliderData} />
      <Instagram />
    </div>
  );
}
